#!/bin/bash

#Key Generator
gcc -std=c99 -Wall keygen.c -o keygen

#Encryptors
gcc otp_enc.c -o otp_enc #Client
gcc otp_enc_d.c -o otp_enc_d # server

#Ddecryptors
gcc otp_dec.c -o otp_dec #Client
gcc otp_dec_d.c -o otp_dec_d # server